### ISSUE TITLE
Strip non ASCII characters

### ISSUE THREAD

**Issue by harryray33** [aloneguid/clipnest#1]
Would it be possible to have the ability to strip out non ASCII character from the text?
Also, strip out tags from HTML?

**Comment by aloneguid** [comment]
This is a really good idea. Will add next week!

**Comment by harryray33** [comment]
Thanks, that would be so useful, it mat be worth, if possible, an option of ASCII characters to exclude as well. Similare to a piece of software called Bintext.
![bintext](https://user-images.githubusercontent.com/42322725/198078847-3cd80c96-5274-4331-8ab3-ebe14bcde50e.JPG)

**Comment by aloneguid** [comment]
just added both of those in the latest release!

**Comment by harryray33** [comment]
That's brilliant, thanks...I'll give it a try.
